<style> .skin { background-color:red; font-weight:bold;} .rowheader { background-color:#394fbc; color:white; font-weight:bold; font-size:10pt; } .row1 { background-color:87cefa; } .row2 { background-color:fff8dc; } .row3 { background-color:e0eee0; } .row4 { background-color:e6e6fa; } .row5 { background-color:deb887; } .row6 { background-color:f0e68c; } .row7 { background-color:ffa500; } .row8 { background-color:ff1493; } .row9 { background-color:d8bfd8; } .row10 { background-color:dccdc; } table { background-color:black; } </style><body><center><b>Monster 2005</b><br><br><table cellpadding=2 cellspacing=1 border=0>
<tr class=rowheader><td class=rowheader>#</td><td class=rowheader align=center><b>Name</b></td><td class=rowheader align=center><b>Flight</b></td></tr>
<tr class=row1><td align=center class=row1>1</td><td class=row1>Aaron Wald, Brian Giesinger</td><td class=row1>1st</td></tr>
<tr class=row4><td align=center class=row4>2</td><td class=row4>Al Loftis, Jim Larkin</td><td class=row4>4th</td></tr>
<tr class=row4><td align=center class=row4>3</td><td class=row4>Alden Lorimor, Terry Wright</td><td class=row4>4th</td></tr>
<tr class=row4><td align=center class=row4>4</td><td class=row4>Andy Ness, Nate Bess</td><td class=row4>4th</td></tr>
<tr class=row4><td align=center class=row4>5</td><td class=row4>Ann Larkin, Laura Roseleip</td><td class=row4>4th</td></tr>
<tr class=row3><td align=center class=row3>6</td><td class=row3>Bart Eldredge, Ken Young</td><td class=row3>3rd</td></tr>
<tr class=row4><td align=center class=row4>7</td><td class=row4>Beth Wallace, Patti Wald</td><td class=row4>4th</td></tr>
<tr class=row2><td align=center class=row2>8</td><td class=row2>Bill Bearden, Wayne Podolak</td><td class=row2>2nd</td></tr>
<tr class=row2><td align=center class=row2>9</td><td class=row2>Brent Vogel, Corey Johnson</td><td class=row2>2nd</td></tr>
<tr class=row1><td align=center class=row1>10</td><td class=row1>Chad Wade, Steve Murdock</td><td class=row1>1st</td></tr>
<tr class=row1><td align=center class=row1>11</td><td class=row1>Chris Jones, Doug Wald</td><td class=row1>1st</td></tr>
<tr class=row4><td align=center class=row4>12</td><td class=row4>Colette Podolak, Debbie Borreson</td><td class=row4>4th</td></tr>
<tr class=row4><td align=center class=row4>13</td><td class=row4>Danette Proszek, Mike Summers</td><td class=row4>4th</td></tr>
<tr class=row3><td align=center class=row3>14</td><td class=row3>Daren Proszek, Tom Proszek</td><td class=row3>3rd</td></tr>
<tr class=row2><td align=center class=row2>15</td><td class=row2>Dave Sahli, Steve Wald</td><td class=row2>2nd</td></tr>
<tr class=row3><td align=center class=row3>16</td><td class=row3>Dave Slezak, Mitch Holcomb</td><td class=row3>3rd</td></tr>
<tr class=row3><td align=center class=row3>17</td><td class=row3>Dave Stork, Rick Becker</td><td class=row3>3rd</td></tr>
<tr class=row3><td align=center class=row3>18</td><td class=row3>Dewey Wald, Paul Beitner</td><td class=row3>3rd</td></tr>
<tr class=row2><td align=center class=row2>19</td><td class=row2>Dick Lavin, Tom McCann</td><td class=row2>2nd</td></tr>
<tr class=row3><td align=center class=row3>20</td><td class=row3>Eric Bartsch, Jason Bartsch</td><td class=row3>3rd</td></tr>
<tr class=row4><td align=center class=row4>21</td><td class=row4>Galen Meysenberg, Jesse Hough</td><td class=row4>4th</td></tr>
<tr class=row1><td align=center class=row1>22</td><td class=row1>Jake Jorde, Trevor Spangler</td><td class=row1>1st</td></tr>
<tr class=row2><td align=center class=row2>23</td><td class=row2>Jay Pesicka, Mike Benson</td><td class=row2>2nd</td></tr>
<tr class=row1><td align=center class=row1>24</td><td class=row1>Jeff Haseleu, Scott Anderson</td><td class=row1>1st</td></tr>
<tr class=row1><td align=center class=row1>25</td><td class=row1>Jeff Herberger, Paul Olsen</td><td class=row1>1st</td></tr>
<tr class=row2><td align=center class=row2>26</td><td class=row2>Jeff Wald, Jim Reine</td><td class=row2>2nd</td></tr>
<tr class=row1><td align=center class=row1>27</td><td class=row1>Jim Clark, Mike Levitt</td><td class=row1>1st</td></tr>
<tr class=row2><td align=center class=row2>28</td><td class=row2>Joel VanDyk, John Blackburn</td><td class=row2>2nd</td></tr>
<tr class=row2><td align=center class=row2>29</td><td class=row2>Kirk Redfern, Pat Evenson</td><td class=row2>2nd</td></tr>
<tr class=row3><td align=center class=row3>30</td><td class=row3>Matt Jones, Rick Levitt</td><td class=row3>3rd</td></tr>
<tr class=row3><td align=center class=row3>31</td><td class=row3>Mike Borreson, Scott Hanson</td><td class=row3>3rd</td></tr>
<tr class=row4><td align=center class=row4>32</td><td class=row4>Mike Roseleip, Ryan Thomas</td><td class=row4>4th</td></tr>
<tr class=row3><td align=center class=row3>33</td><td class=row3>Mike Stork, Randy Carlson</td><td class=row3>3rd</td></tr>
<tr class=row3><td align=center class=row3>34</td><td class=row3>Neil Hefta, Steve McAndrew</td><td class=row3>3rd</td></tr>
<tr class=row2><td align=center class=row2>35</td><td class=row2>Pat Racanelli, Paul Jaeger</td><td class=row2>2nd</td></tr>
<tr class=row1><td align=center class=row1>36</td><td class=row1>Paul Holmquist, Rich Podolak</td><td class=row1>1st</td></tr>
<tr class=row1><td align=center class=row1>37</td><td class=row1>Shawn Dumphy, William Kwan</td><td class=row1>1st</td></tr>
</table></center>