<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 11">
<link rel=File-List href="PracticeLeaders_files/filelist.xml">
<style id="MonsterScoring2004_20463_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl1520463
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:9.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Tahoma;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl2420463
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:white;
	font-size:9.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:Tahoma, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	border-top:1.0pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:1.0pt solid windowtext;
	background:#3366FF;
	mso-pattern:auto none;
	white-space:nowrap;}
.xl2520463
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:white;
	font-size:9.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:Tahoma, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	border-top:1.0pt solid windowtext;
	border-right:none;
	border-bottom:none;
	border-left:.5pt solid windowtext;
	background:#3366FF;
	mso-pattern:auto none;
	white-space:nowrap;}
.xl2620463
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:9.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:Tahoma, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	border:.5pt solid windowtext;
	background:#FFCC00;
	mso-pattern:auto none;
	white-space:nowrap;}
.xl2720463
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:white;
	font-size:9.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:Tahoma, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	border-top:1.0pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:none;
	border-left:.5pt solid windowtext;
	background:#3366FF;
	mso-pattern:auto none;
	white-space:nowrap;}
.xl2820463
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:9.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:Tahoma, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	border-top:1.0pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:1.0pt solid windowtext;
	background:#FFCC00;
	mso-pattern:auto none;
	white-space:nowrap;}
.xl2920463
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:9.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:Tahoma, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	border-top:.5pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:1.0pt solid windowtext;
	background:#FFCC00;
	mso-pattern:auto none;
	white-space:nowrap;}
.xl3020463
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:9.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:Tahoma, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	border:.5pt solid windowtext;
	background:#99CCFF;
	mso-pattern:auto none;
	white-space:nowrap;}
-->
</style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Office Excel's Publish
as Web Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="MonsterScoring2004_20463" align=center x:publishsource="Excel">

<table x:str border=0 cellpadding=0 cellspacing=0 width=283 style='border-collapse:
 collapse;table-layout:fixed;width:213pt'>
 <col width=51 style='mso-width-source:userset;mso-width-alt:1865;width:38pt'>
 <col width=178 style='mso-width-source:userset;mso-width-alt:6509;width:134pt'>
 <col width=54 style='mso-width-source:userset;mso-width-alt:1974;width:41pt'>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl2420463 width=51 style='height:16.5pt;width:38pt'>Place</td>
  <td class=xl2520463 width=178 style='border-left:none;width:134pt'>Team</td>
  <td class=xl2720463 width=54 style='width:41pt'>Total</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl3020463 style='height:15.75pt;border-top:none'>1</td>
  <td class=xl2620463 style='border-left:none'>Bartsch / Debbie</td>
  <td class=xl2820463>52</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl3020463 style='height:15.75pt;border-top:none'>2</td>
  <td class=xl2620463 style='border-top:none;border-left:none'>Mike Canfield /
  Doug</td>
  <td class=xl2920463 style='border-top:none'>51</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl3020463 style='height:15.75pt;border-top:none'>3</td>
  <td class=xl2620463 style='border-top:none;border-left:none'>Jeff / Al</td>
  <td class=xl2920463 style='border-top:none'>49</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl3020463 style='height:15.75pt;border-top:none'>4</td>
  <td class=xl2620463 style='border-top:none;border-left:none'>Slezak / Bart</td>
  <td class=xl2920463 style='border-top:none'>50</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl3020463 style='height:15.75pt;border-top:none'>5</td>
  <td class=xl2620463 style='border-top:none;border-left:none'>Rich Pod / Ken
  Young</td>
  <td class=xl2920463 style='border-top:none'>47</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl3020463 style='height:15.75pt;border-top:none'>6</td>
  <td class=xl2620463 style='border-top:none;border-left:none'>Dewey / Raymo</td>
  <td class=xl2920463 style='border-top:none'>45</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl3020463 style='height:15.75pt;border-top:none'>7</td>
  <td class=xl2620463 style='border-top:none;border-left:none'>Scott A / Has</td>
  <td class=xl2920463 style='border-top:none'>44</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl3020463 style='height:15.75pt;border-top:none'>8</td>
  <td class=xl2620463 style='border-top:none;border-left:none'>Aaron / Brian
  Lorenz</td>
  <td class=xl2920463 style='border-top:none'>43</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl3020463 style='height:15.75pt;border-top:none'>9</td>
  <td class=xl2620463 style='border-top:none;border-left:none'>Wuss / Stork,
  Dave</td>
  <td class=xl2920463 style='border-top:none'>41</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl3020463 style='height:15.75pt;border-top:none'>10</td>
  <td class=xl2620463 style='border-top:none;border-left:none'>Collette / Gary</td>
  <td class=xl2920463 style='border-top:none'>42</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl3020463 style='height:15.75pt;border-top:none'>11</td>
  <td class=xl2620463 style='border-top:none;border-left:none'>Plem / Carlson</td>
  <td class=xl2920463 style='border-top:none'>41</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl3020463 style='height:15.75pt;border-top:none'>12</td>
  <td class=xl2620463 style='border-top:none;border-left:none'>Brett / Ron</td>
  <td class=xl2920463 style='border-top:none'>40</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl3020463 style='height:15.75pt;border-top:none'>13</td>
  <td class=xl2620463 style='border-top:none;border-left:none'>Grant / Homer</td>
  <td class=xl2920463 style='border-top:none'>39</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl3020463 style='height:15.75pt;border-top:none'>14</td>
  <td class=xl2620463 style='border-top:none;border-left:none'>Lance / Dave
  Sahli</td>
  <td class=xl2920463 style='border-top:none'>39</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl3020463 style='height:15.75pt;border-top:none'>15</td>
  <td class=xl2620463 style='border-top:none;border-left:none'>Bo Bo / Foltz</td>
  <td class=xl2920463 style='border-top:none'>39</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl3020463 style='height:15.75pt;border-top:none'>16</td>
  <td class=xl2620463 style='border-top:none;border-left:none'>Brad Krogstad /
  Thad</td>
  <td class=xl2920463 style='border-top:none'>38</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl3020463 style='height:15.75pt;border-top:none'>17</td>
  <td class=xl2620463 style='border-top:none;border-left:none'>Rick Becker /
  Tufto</td>
  <td class=xl2920463 style='border-top:none'>38</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl3020463 style='height:15.75pt;border-top:none'>18</td>
  <td class=xl2620463 style='border-top:none;border-left:none'>Jim Clark / Andy
  Ness</td>
  <td class=xl2920463 style='border-top:none'>38</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl3020463 style='height:15.75pt;border-top:none'>19</td>
  <td class=xl2620463 style='border-top:none;border-left:none'>Rob / Tom</td>
  <td class=xl2920463 style='border-top:none'>38</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl3020463 style='height:15.75pt;border-top:none'>20</td>
  <td class=xl2620463 style='border-top:none;border-left:none'>Levitt / Jim
  Lavin</td>
  <td class=xl2920463 style='border-top:none'>37</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl3020463 style='height:15.75pt;border-top:none'>21</td>
  <td class=xl2620463 style='border-top:none;border-left:none'>Wayne / Paul
  Beitner</td>
  <td class=xl2920463 style='border-top:none'>35</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl3020463 style='height:15.75pt;border-top:none'>22</td>
  <td class=xl2620463 style='border-top:none;border-left:none'>Stork, Mike /
  Bass</td>
  <td class=xl2920463 style='border-top:none'>32</td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=51 style='width:38pt'></td>
  <td width=178 style='width:134pt'></td>
  <td width=54 style='width:41pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
